/* Generated by scripts/build-smart-packaging-component-catalog-completion.ts. */
export const SMART_PACKAGING_FINAL_CLOSURE_MANIFEST_SHA256_V1 = "a319c3ab69c9b1040894921896e17c4f2e09c12ca53cfb47a126555ba5b296e9" as const;

export const SMART_PACKAGING_CATALOG_COMPLETION_RECORDS_V1 = [
  {
    "coreId": "border-light-trace",
    "implementationId": "catalog-completion:v1:border-light-trace",
    "label": "边框流光描边",
    "target": "LOCAL_ANNOTATION",
    "renderFamily": "ANNOTATION",
    "roleConstraint": "SUPPORT_ONLY",
    "requiredEvidence": [
      "BOUND_TARGET_RECT",
      "MOTION_REASON"
    ],
    "inputContract": {
      "requiredProps": [
        "content",
        "targetRect"
      ],
      "optionalProps": [
        "label",
        "accentColor",
        "cornerRadius",
        "direction",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": 40
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "保留目标框和一条稳定的高亮边，不持续绕行。"
    },
    "rationale": "补齐沿已绑定对象边缘运行的光带机制；它不是场景氛围，也不能自行选择目标。",
    "sourceEffectUnitIds": [
      "candidate:cv-sceneglow",
      "shotcraft:neon-frame-forerun:neon-frame-forerun",
      "shotcraft:neon-frame-orbit-drop:neon-frame-orbit-drop"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/code-ui-cores.tsx",
      "exportName": "CompletionAnnotationCore",
      "fileSha256": "25334ca3aef1a19eeedc785a9326c00bec8ea0386e7c7f47cf4e4c72cd205d60"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "chat-thread",
    "implementationId": "catalog-completion:v1:chat-thread",
    "label": "对话线程",
    "target": "SCREEN_UI",
    "renderFamily": "CODE_UI",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "APPROVED_MESSAGE_SEQUENCE"
    ],
    "inputContract": {
      "requiredProps": [
        "messages"
      ],
      "optionalProps": [
        "activeMessageId",
        "title",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 12,
        "maximumTextCharacters": 720
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示全部已批准消息、角色与顺序，不模拟继续生成。"
    },
    "rationale": "对话气泡的角色、顺序和逐条揭示具有独立输入合同，不能由普通文字卡等价替代。",
    "sourceEffectUnitIds": [
      "candidate:ai-chat-reveal",
      "candidate:chat-thread",
      "candidate:cv-minidashboard",
      "candidate:ec-remocn",
      "candidate:ec-remocn-chat",
      "candidate:hf-chatgpt-claude",
      "candidate:rc-chatflow",
      "candidate:rc-chatgpt",
      "candidate:rc-chattopreview",
      "candidate:snap-answer-stream"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/code-ui-cores.tsx",
      "exportName": "CompletionCodeUiCore",
      "fileSha256": "25334ca3aef1a19eeedc785a9326c00bec8ea0386e7c7f47cf4e4c72cd205d60"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "code-block",
    "implementationId": "catalog-completion:v1:code-block",
    "label": "代码面板",
    "target": "SCREEN_UI",
    "renderFamily": "CODE_UI",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "APPROVED_CODE_TEXT"
    ],
    "inputContract": {
      "requiredProps": [
        "lines"
      ],
      "optionalProps": [
        "language",
        "title",
        "lineNumbers",
        "accentColor",
        "depth",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 28,
        "maximumTextCharacters": 1800
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "完整显示经过批准的代码行并保持行号、缩进和语言标签。"
    },
    "rationale": "代码是独立的信息对象；主题和三维外观只是受控 preset，不能替代代码内容合同。",
    "sourceEffectUnitIds": [
      "candidate:code-snippet-apple-terminal-pro",
      "candidate:ec-remocn-terminal",
      "candidate:hf-apple-terminal",
      "candidate:hf-code-3d-extrude",
      "candidate:rc-glasscodeblock"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/code-ui-cores.tsx",
      "exportName": "CompletionCodeUiCore",
      "fileSha256": "25334ca3aef1a19eeedc785a9326c00bec8ea0386e7c7f47cf4e4c72cd205d60"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "code-diff",
    "implementationId": "catalog-completion:v1:code-diff",
    "label": "代码差异",
    "target": "SCREEN_UI",
    "renderFamily": "CODE_UI",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "APPROVED_CODE_DIFF"
    ],
    "inputContract": {
      "requiredProps": [
        "lines"
      ],
      "optionalProps": [
        "title",
        "activeLineIndex",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 32,
        "maximumTextCharacters": 2200
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "并列保留新增、删除和上下文行，不生成不存在的代码变更。"
    },
    "rationale": "新增、删除和上下文语义需要专用输入合同，不能降格为单纯代码高亮。",
    "sourceEffectUnitIds": [
      "candidate:code-diff",
      "candidate:ec-onda-codediff",
      "candidate:od-codediff",
      "candidate:ro-tpl-codehike"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/code-ui-cores.tsx",
      "exportName": "CompletionCodeUiCore",
      "fileSha256": "25334ca3aef1a19eeedc785a9326c00bec8ea0386e7c7f47cf4e4c72cd205d60"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "code-focus",
    "implementationId": "catalog-completion:v1:code-focus",
    "label": "代码聚焦与滚动",
    "target": "SCREEN_UI",
    "renderFamily": "CODE_UI",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "APPROVED_CODE_TEXT",
      "BOUND_CODE_RANGE"
    ],
    "inputContract": {
      "requiredProps": [
        "lines",
        "activeLineIndex"
      ],
      "optionalProps": [
        "title",
        "mode",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 48,
        "maximumTextCharacters": 3200
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示完整代码并稳定突出已绑定行，不自动滚动。"
    },
    "rationale": "代码滚动和行级聚焦共享同一范围绑定与可读性合同，作为一个 Core 的两个受控 preset。",
    "sourceEffectUnitIds": [
      "candidate:code-highlight",
      "candidate:ec-remocn-terminal",
      "candidate:hf-code-scroll",
      "candidate:ro-tpl-codehike"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/code-ui-cores.tsx",
      "exportName": "CompletionCodeUiCore",
      "fileSha256": "25334ca3aef1a19eeedc785a9326c00bec8ea0386e7c7f47cf4e4c72cd205d60"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "icon-cloud",
    "implementationId": "catalog-completion:v1:icon-cloud",
    "label": "图标关系云",
    "target": "RELATION_STRUCTURE",
    "renderFamily": "RELATION",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "APPROVED_ENTITY_SET"
    ],
    "inputContract": {
      "requiredProps": [
        "items"
      ],
      "optionalProps": [
        "activeId",
        "seed",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 4,
        "maximumItems": 32,
        "maximumTextCharacters": 320
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "以可辨识的固定关系云显示全部实体和当前重点。"
    },
    "rationale": "多实体围绕中心或球面分布是独立关系表达，不等同于二维列表或普通媒体轮播。",
    "sourceEffectUnitIds": [
      "candidate:pw-iconcloud"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/media-data-cores.tsx",
      "exportName": "CompletionRelationCore",
      "fileSha256": "24a666805144a4a9b7a7d034794ba19b7809a1774ed39781a73ceb1c081fd64b"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "map-data",
    "implementationId": "catalog-completion:v1:map-data",
    "label": "地图数据标注",
    "target": "QUANT_DATA",
    "renderFamily": "DATA",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "BOUND_MAP_GEOMETRY",
      "NUMBER_OR_LOCATION_DATA"
    ],
    "inputContract": {
      "requiredProps": [
        "regions",
        "title"
      ],
      "optionalProps": [
        "unit",
        "activeRegionId",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 24,
        "maximumTextCharacters": 480
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示完整地图轮廓、真实位置和数据标签。"
    },
    "rationale": "地理位置和区域值需要地图几何绑定，不能由普通关系图或散点图替代。",
    "sourceEffectUnitIds": [
      "candidate:hf-world-map"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/media-data-cores.tsx",
      "exportName": "CompletionDataCore",
      "fileSha256": "24a666805144a4a9b7a7d034794ba19b7809a1774ed39781a73ceb1c081fd64b"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "media-pan-zoom",
    "implementationId": "catalog-completion:v1:media-pan-zoom",
    "label": "媒体平移推拉",
    "target": "MEDIA_EVIDENCE",
    "renderFamily": "MEDIA",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "BOUND_MEDIA",
      "BOUND_FOCUS_REGION"
    ],
    "inputContract": {
      "requiredProps": [
        "content",
        "start",
        "end"
      ],
      "optionalProps": [
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示完整媒体并以终点焦区为轻微稳定构图。"
    },
    "rationale": "Ken Burns、平移和轻推近共享一条受源边界约束的媒体相机轨迹合同。",
    "sourceEffectUnitIds": [
      "candidate:od-kenburns",
      "candidate:pj-kenburns",
      "candidate:rve-templates-ken-burns-tsx",
      "candidate:rve-templates-parallax-pan-tsx"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/media-data-cores.tsx",
      "exportName": "CompletionMediaCore",
      "fileSha256": "24a666805144a4a9b7a7d034794ba19b7809a1774ed39781a73ceb1c081fd64b"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "media-treatment",
    "implementationId": "catalog-completion:v1:media-treatment",
    "label": "媒体后期处理",
    "target": "MEDIA_EVIDENCE",
    "renderFamily": "MEDIA",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "BOUND_MEDIA",
      "TREATMENT_REASON"
    ],
    "inputContract": {
      "requiredProps": [
        "content",
        "mode"
      ],
      "optionalProps": [
        "accentColor",
        "amount",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "保留原媒体，仅应用稳定且可逆的轻量纹理或边缘处理。"
    },
    "rationale": "颗粒、扫描线、半调、暗角和受控模糊是媒体处理 preset，不应被误算成五个内容组件。",
    "sourceEffectUnitIds": [
      "candidate:caption-neon-glow",
      "candidate:cv-bulbbg",
      "candidate:grain-overlay",
      "candidate:lt-neon-border",
      "candidate:pj-cinematic",
      "candidate:pj-neon",
      "candidate:rc-perlinnoise",
      "candidate:ro-effects",
      "candidate:ro-noise",
      "candidate:rs-background-grid",
      "candidate:rs-effects",
      "candidate:rs-textneon",
      "candidate:rve-templates-grid-pulse-tsx",
      "candidate:rve-templates-matrix-rain-tsx",
      "candidate:rve-templates-noise-grain-tsx",
      "candidate:rve-templates-vignette-pulse-tsx",
      "candidate:scenes-src-scenes-backgroundanimations-backgroundgeometric-tsx",
      "candidate:scenes-src-scenes-backgroundanimations-backgroundnoisetexture-tsx",
      "candidate:scenes-src-scenes-backgroundanimations-backgroundperspectivegrid-tsx",
      "candidate:scenes-src-scenes-backgroundanimations-backgroundradial-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicaction-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicanime-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicdocumentary-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicepic-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematichorror-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicminimalend-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicnoir-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicromance-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicscifi-tsx",
      "candidate:scenes-src-scenes-cinematicanimations-cinematicvintage-tsx",
      "candidate:scenes-src-scenes-effectanimations-effectfilmgrain-tsx",
      "candidate:scenes-src-scenes-effectanimations-effectmatrix-tsx",
      "candidate:scenes-src-scenes-effectanimations-effectnoise-tsx",
      "candidate:scenes-src-scenes-logoanimations-logoneonsign-tsx",
      "candidate:scenes-src-scenes-shapeanimations-shapehexgrid-tsx",
      "candidate:scenes-src-scenes-shapeanimations-shapemandala-tsx",
      "candidate:scenes-src-scenes-shapeanimations-shapespinningrings-tsx",
      "candidate:scenes-src-scenes-themeanimations-theme3dglassthreejs-tsx",
      "candidate:scenes-src-scenes-themeanimations-themeneon-tsx",
      "shotcraft:neon-triple-marquee:neon-triple-marquee"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/media-data-cores.tsx",
      "exportName": "CompletionMediaCore",
      "fileSha256": "24a666805144a4a9b7a7d034794ba19b7809a1774ed39781a73ceb1c081fd64b"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "metric-card",
    "implementationId": "catalog-completion:v1:metric-card",
    "label": "指标卡",
    "target": "QUANT_DATA",
    "renderFamily": "DATA",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "NUMBER_DATA",
      "METRIC_LABEL"
    ],
    "inputContract": {
      "requiredProps": [
        "label",
        "value"
      ],
      "optionalProps": [
        "unit",
        "delta",
        "trend",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": 80
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示真实数值、单位、指标名和可选变化方向。"
    },
    "rationale": "单指标卡的数值、单位与趋势语义不同于纯计数动画，需独立容量和证据合同。",
    "sourceEffectUnitIds": [
      "candidate:cv-statsgrid",
      "candidate:ec-remocn-github",
      "candidate:od-statcard",
      "candidate:ro-tpl-stargazer",
      "candidate:scenes-src-scenes-dataanimations-datastatscards-tsx",
      "candidate:scenes-src-scenes-listanimations-liststatsfocused-tsx"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/media-data-cores.tsx",
      "exportName": "CompletionDataCore",
      "fileSha256": "24a666805144a4a9b7a7d034794ba19b7809a1774ed39781a73ceb1c081fd64b"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "perspective-grid",
    "implementationId": "catalog-completion:v1:perspective-grid",
    "label": "透视网格场景",
    "target": "SCENE_SURFACE",
    "renderFamily": "SCENE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "requiredEvidence": [
      "BOUND_CONTENT",
      "MOTION_REASON"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "horizon",
        "density",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "保留内容并显示固定、低对比度透视网格。"
    },
    "rationale": "透视网格具有独立空间和运动参数，但永远只是已绑定内容的场景表面。",
    "sourceEffectUnitIds": [
      "candidate:dynamic-grid",
      "candidate:pw-techgrid"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/media-data-cores.tsx",
      "exportName": "CompletionSceneCore",
      "fileSha256": "24a666805144a4a9b7a7d034794ba19b7809a1774ed39781a73ceb1c081fd64b"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "step-progress",
    "implementationId": "catalog-completion:v1:step-progress",
    "label": "步骤进度",
    "target": "RELATION_STRUCTURE",
    "renderFamily": "RELATION",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "requiredEvidence": [
      "APPROVED_STEP_SEQUENCE"
    ],
    "inputContract": {
      "requiredProps": [
        "steps",
        "activeStepId"
      ],
      "optionalProps": [
        "orientation",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 8,
        "maximumTextCharacters": 320
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示全部步骤、固定顺序和当前状态。"
    },
    "rationale": "步骤状态需要 completed/current/pending 合同，不等同于单一百分比进度条。",
    "sourceEffectUnitIds": [
      "candidate:od-progresssteps",
      "candidate:scenes-src-scenes-demoanimations-demowizard-tsx"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/media-data-cores.tsx",
      "exportName": "CompletionRelationCore",
      "fileSha256": "24a666805144a4a9b7a7d034794ba19b7809a1774ed39781a73ceb1c081fd64b"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "stroke-trace",
    "implementationId": "catalog-completion:v1:stroke-trace",
    "label": "路径描绘",
    "target": "LOCAL_ANNOTATION",
    "renderFamily": "ANNOTATION",
    "roleConstraint": "SUPPORT_ONLY",
    "requiredEvidence": [
      "BOUND_VECTOR_PATH",
      "BOUND_TARGET"
    ],
    "inputContract": {
      "requiredProps": [
        "path",
        "viewBox"
      ],
      "optionalProps": [
        "label",
        "strokeWidth",
        "accentColor",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": 40
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示完整矢量路径和目标标签。"
    },
    "rationale": "任意 SVG/白板路径的逐段描绘需要路径长度合同，不能限定为箭头、圆或下划线。",
    "sourceEffectUnitIds": [
      "candidate:rc-handwrite",
      "candidate:svg-stroke-trace",
      "candidate:vs-drawsvgtrace",
      "candidate:whiteboard-ink"
    ],
    "implementation": {
      "path": "desktop/component-lab/catalog-completion/code-ui-cores.tsx",
      "exportName": "CompletionAnnotationCore",
      "fileSha256": "25334ca3aef1a19eeedc785a9326c00bec8ea0386e7c7f47cf4e4c72cd205d60"
    },
    "lifecycle": "DRAFT",
    "visibility": "LAB_ONLY",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": false,
    "productUserAccepted": false
  }
] as const;

export const SMART_PACKAGING_FINAL_CLOSURE_SUMMARY_V1 = {
  "totalEffectUnits": 797,
  "resolvedEffectUnits": 797,
  "unresolvedEffectUnits": 0,
  "independentlyComponentizableEffectUnits": 626,
  "nonComponentEffectUnits": 171,
  "byDisposition": {
    "AGGREGATE_COVERED": 40,
    "COMPONENT_COVERED": 626,
    "COMPOSITE_COVERED": 52,
    "LAYOUT_REFERENCE_ONLY": 12,
    "MEDIA_ADAPTER_NOT_COMPONENT": 2,
    "STYLE_REFERENCE_ONLY": 50,
    "TOOLING_NOT_COMPONENT": 15
  },
  "finalIndependentComponents": 108,
  "existingIndependentComponents": 95,
  "newlyImplementedIndependentComponents": 13,
  "newComponentsByTarget": {
    "LOCAL_ANNOTATION": 2,
    "MEDIA_EVIDENCE": 2,
    "QUANT_DATA": 2,
    "RELATION_STRUCTURE": 2,
    "SCENE_SURFACE": 1,
    "SCREEN_UI": 4
  },
  "legacyRunnableResolved": 24,
  "parameterAdapterResolved": 18,
  "outsideCalibrationUnknownResolved": 48,
  "sourceRuntimeBlocksResolvedByReimplementation": 4,
  "agentVisible": 0,
  "productionReady": 0
} as const;

export type SmartPackagingCatalogCompletionGeneratedRecordV1 = (typeof SMART_PACKAGING_CATALOG_COMPLETION_RECORDS_V1)[number];
