/* Generated by scripts/build-smart-packaging-component-new-core-lab.ts. */
export const SMART_PACKAGING_NEW_CORE_LAB_MANIFEST_SHA256_V1 = "a7e5fb08669020b0ff6f90e9387ebbd60e3846c2c2b3bb850c21ca307b3ea6aa" as const;

export const SMART_PACKAGING_NEW_CORE_LAB_REVIEW_V1 = {
  "schemaVersion": 1,
  "verificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
  "reviewedOn": "2026-08-31",
  "reviewedImplementationCommit": "89873e29f17b5f01ca813a87165ccb6d0327f679",
  "reviewedDraftManifestSha256": "6f36793779cd7cec9e3be1b85e79efc63011a49a618dce6eb479a25a1367d933",
  "automatedTestRunId": "test-run:desktop-vitest:89873e29:347-passed-1-skipped",
  "labPreviewHash": "94647be68c181aefd35790492b765275e3020353bf6dff771c74179387351323",
  "labReviewDecisionId": "decision:smart-packaging-new-core-lab-v1:user-approved-all-21:2026-08-31",
  "targetFormat": "LANDSCAPE",
  "controlledFixtureOnly": true,
  "browserVerification": {
    "dynamicMountPassed": 21,
    "dynamicMountFailed": 0,
    "reducedMotionMountPassed": 21,
    "reducedMotionMountFailed": 0,
    "consoleErrors": 0,
    "consoleWarnings": 0
  },
  "acceptedPreviewFiles": [
    {
      "path": "desktop/component-lab/new-cores/camera-boundary-cores.tsx",
      "sha256": "6c79a5525f7ec53dd57fa5d6629c3f3c8057c38a9a28c0004d29a4282308719b"
    },
    {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "sha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    {
      "path": "desktop/component-lab/new-cores/renderers.tsx",
      "sha256": "6970abfc23556ac011952639cf6b025f6c6d50e927a6a64e541acda3d8a07681"
    },
    {
      "path": "desktop/component-lab/new-cores/shared.tsx",
      "sha256": "dd2134d789a3490c6190846b83e2a0be62d05b725b590276acba8ee268c0bb7c"
    },
    {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "sha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    }
  ],
  "verifiedCoreIds": [
    "area-chart",
    "camera-orbit",
    "camera-shake",
    "channel-distortion",
    "clock-dial",
    "color-treatment",
    "credits-roll",
    "cross-dissolve",
    "kaleidoscope-symmetry",
    "light-overlay",
    "liquid-blob",
    "liquid-flow",
    "liquid-ink",
    "liquid-ripple",
    "liquid-surface",
    "liquid-swirl",
    "liquid-transition",
    "loader-indicator",
    "media-frame",
    "media-grid",
    "radial-chart"
  ]
} as const;

export const SMART_PACKAGING_NEW_CORE_LAB_RECORDS_V1 = [
  {
    "coreId": "area-chart",
    "researchImplementationId": "new-core-lab:v1:area-chart",
    "sourceGroupId": "new:area-chart",
    "label": "面积趋势图",
    "batch": "OBJECT_CORE",
    "target": "QUANT_DATA",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "semanticSlots": [
      "COLOR_THEME",
      "DATA_POINTS"
    ],
    "requiredEvidence": [
      "NUMBER_OR_TIME_DATA"
    ],
    "inputContract": {
      "requiredProps": [
        "data",
        "title",
        "unit"
      ],
      "optionalProps": [
        "accentColor",
        "intensity",
        "reducedMotion",
        "showGrid"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 12,
        "maximumTextCharacters": 48
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示完整面积、边界线、轴标签和结论值。"
    },
    "mechanismSummary": "用面积填充与边界线表达可核查数据序列的趋势，不从文案语气生成数据。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "exportName": "AreaChartCore",
      "fileSha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:rve-templates-area-chart-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/area-chart.tsx",
        "sourceSha256": "7c039cfde4b8d5a7fd45a4f69736cef3e887192d3d7d384d977c75be706fe0de",
        "sourceLineCount": 233,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "clock-dial",
    "researchImplementationId": "new-core-lab:v1:clock-dial",
    "sourceGroupId": "new:clock-dial",
    "label": "时钟表盘",
    "batch": "OBJECT_CORE",
    "target": "QUANT_DATA",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "semanticSlots": [
      "CLOCK_VALUE",
      "COLOR_THEME"
    ],
    "requiredEvidence": [
      "NUMBER_OR_TIME_DATA"
    ],
    "inputContract": {
      "requiredProps": [
        "hour",
        "minute",
        "second"
      ],
      "optionalProps": [
        "accentColor",
        "intensity",
        "label",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": null,
        "maximumItems": null,
        "maximumTextCharacters": 32
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "直接显示输入时间对应的最终指针位置。"
    },
    "mechanismSummary": "把受控时间值映射到刻度与三根指针，不读取系统墙钟。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "exportName": "ClockDialCore",
      "fileSha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:playground-src-compositions-clockanimations-analogclock-jsx",
        "sourcePath": "src/vendor/upstream/playground/src/compositions/ClockAnimations/AnalogClock.tsx",
        "sourceSha256": "1f7915fb9b1a29fa8ddc62948190e50008d7dc8326d855b0734093f7c16a9441",
        "sourceLineCount": 219,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "color-treatment",
    "researchImplementationId": "new-core-lab:v1:color-treatment",
    "sourceGroupId": "new:color-treatment",
    "label": "受控双色调",
    "batch": "OBJECT_CORE",
    "target": "MEDIA_EVIDENCE",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "semanticSlots": [
      "COLOR_THEME",
      "MEDIA_NODE"
    ],
    "requiredEvidence": [
      "MEDIA_ASSET"
    ],
    "inputContract": {
      "requiredProps": [
        "content",
        "highlightColor",
        "shadowColor"
      ],
      "optionalProps": [
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "保留媒体并应用固定、低强度的双色调终态。"
    },
    "mechanismSummary": "用可限制强度的混合叠层处理真实媒体，同时保留其结构与证据含义。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "exportName": "ColorTreatmentCore",
      "fileSha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-effectanimations-effectduotone-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/EffectAnimations/EffectDuotone.tsx",
        "sourceSha256": "b3e83f66f54095e25f0a562f254674bb6edd3a45706c5e9a84d063a79e0876ae",
        "sourceLineCount": 113,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "credits-roll",
    "researchImplementationId": "new-core-lab:v1:credits-roll",
    "sourceGroupId": "new:credits-roll",
    "label": "连续纵向字幕卷轴",
    "batch": "OBJECT_CORE",
    "target": "TEXT_INFO",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "semanticSlots": [
      "COLOR_THEME",
      "TEXT_ENTRIES"
    ],
    "requiredEvidence": [
      "TEXT_BINDING"
    ],
    "inputContract": {
      "requiredProps": [
        "entries",
        "title"
      ],
      "optionalProps": [
        "accentColor",
        "footer",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 18,
        "maximumTextCharacters": 42
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示分页后的代表性条目与总数，不执行连续滚动。"
    },
    "mechanismSummary": "按可读速度连续呈现姓名/职位或条目列表，并显式限制容量。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "exportName": "CreditsRollCore",
      "fileSha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:rve-templates-credits-roll-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/credits-roll.tsx",
        "sourceSha256": "ee56a327f71e701483e99cb8115f913560ee079808924ec329c487b8d30ed6cb",
        "sourceLineCount": 107,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "loader-indicator",
    "researchImplementationId": "new-core-lab:v1:loader-indicator",
    "sourceGroupId": "new:loader-indicator",
    "label": "加载状态指示器",
    "batch": "OBJECT_CORE",
    "target": "SCREEN_UI",
    "roleConstraint": "SUPPORT_ONLY",
    "semanticSlots": [
      "COLOR_THEME",
      "UI_STATE"
    ],
    "requiredEvidence": [
      "UI_SEGMENT",
      "UI_STATE_EVIDENCE"
    ],
    "inputContract": {
      "requiredProps": [
        "label",
        "state"
      ],
      "optionalProps": [
        "accentColor",
        "intensity",
        "progress",
        "reducedMotion",
        "variant"
      ],
      "capacity": {
        "minimumItems": null,
        "maximumItems": null,
        "maximumTextCharacters": 32
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示静态状态环、真实进度或明确等待标签。"
    },
    "mechanismSummary": "呈现真实 loading/progress UI 状态，不把循环图形当作无语义装饰。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "exportName": "LoaderIndicatorCore",
      "fileSha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:pj-spinners",
        "sourcePath": "src/vendor/upstream/playground/src/compositions/LoadingAnimations/Spinners.tsx",
        "sourceSha256": "49cc1117b2822d807e4a3165e410866b73de408bfcfed334c28f6d5763d26310",
        "sourceLineCount": 290,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-uianimations-uiloading-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/UIAnimations/UILoading.tsx",
        "sourceSha256": "3b98c2f9260aa1421edf0792dab1921fe83a9123a7559386aadf98a6a9ac92b9",
        "sourceLineCount": 142,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "media-frame",
    "researchImplementationId": "new-core-lab:v1:media-frame",
    "sourceGroupId": "new:media-frame",
    "label": "可参数化媒体相框",
    "batch": "OBJECT_CORE",
    "target": "MEDIA_EVIDENCE",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "semanticSlots": [
      "COLOR_THEME",
      "MEDIA_NODE",
      "TEXT_ENTRIES"
    ],
    "requiredEvidence": [
      "MEDIA_ASSET"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "accentColor",
        "caption",
        "intensity",
        "reducedMotion",
        "sourceLabel"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": 64
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "直接显示完整媒体、相框和来源标签。"
    },
    "mechanismSummary": "为真实媒体提供不改变证据含义的框体、来源和从属注释。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "exportName": "MediaFrameCore",
      "fileSha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:rve-templates-polaroid-frame-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/polaroid-frame.tsx",
        "sourceSha256": "0bfc388f0023cd5e527d6364a5305d92954e879633c2f887302e62e48afaf97f",
        "sourceLineCount": 73,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "media-grid",
    "researchImplementationId": "new-core-lab:v1:media-grid",
    "sourceGroupId": "new:media-grid",
    "label": "媒体网格",
    "batch": "OBJECT_CORE",
    "target": "MEDIA_EVIDENCE",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "semanticSlots": [
      "COLOR_THEME",
      "MEDIA_ITEMS",
      "TEXT_ENTRIES"
    ],
    "requiredEvidence": [
      "MEDIA_ASSET"
    ],
    "inputContract": {
      "requiredProps": [
        "items"
      ],
      "optionalProps": [
        "accentColor",
        "columns",
        "intensity",
        "layout",
        "reducedMotion",
        "title"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 9,
        "maximumTextCharacters": 32
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示稳定网格及全部可见媒体项。"
    },
    "mechanismSummary": "在受控容量内编排多份真实媒体，并保持顺序、焦点和来源身份。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "exportName": "MediaGridCore",
      "fileSha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:rve-templates-gallery-grid-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/gallery-grid.tsx",
        "sourceSha256": "f6c212eb1834dbadbae73e8281c9e8ca3b32f4ea8a865224879f90c3efe8ed55",
        "sourceLineCount": 70,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:rve-templates-masonry-gallery-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/masonry-gallery.tsx",
        "sourceSha256": "2d3ab09648d0e385d9a123cdb048d5413ae820205e1bd04afd08b12dd683a29d",
        "sourceLineCount": 83,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "radial-chart",
    "researchImplementationId": "new-core-lab:v1:radial-chart",
    "sourceGroupId": "new:radial-chart",
    "label": "径向分区图",
    "batch": "OBJECT_CORE",
    "target": "QUANT_DATA",
    "roleConstraint": "MAIN_OR_SUPPORT",
    "semanticSlots": [
      "COLOR_THEME",
      "DATA_POINTS"
    ],
    "requiredEvidence": [
      "NUMBER_OR_TIME_DATA"
    ],
    "inputContract": {
      "requiredProps": [
        "segments",
        "title",
        "unit"
      ],
      "optionalProps": [
        "centerLabel",
        "intensity",
        "mode",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 6,
        "maximumTextCharacters": 32
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示完整分区、图例、总量与单位。"
    },
    "mechanismSummary": "把有限分类值映射为可比较的环形或饼形分区，并保留总量与单位。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/object-cores.tsx",
      "exportName": "RadialChartCore",
      "fileSha256": "00455977af7afcef43f81db9ea5efac0336d2654007932d4bdddd4a0d8b9581a"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:rve-templates-donut-chart-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/donut-chart.tsx",
        "sourceSha256": "22d31bd3db502cef788ad32f3dc4ffbba2f135843c6aaac8650c360d22d34590",
        "sourceLineCount": 216,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:rve-templates-pie-chart-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/pie-chart.tsx",
        "sourceSha256": "f92339b6fb8794fb9dd9e7ed2e53fb0380ff44543563a9fa8ca40210feb4ca09",
        "sourceLineCount": 175,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-dataanimations-datapiechart-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/DataAnimations/DataPieChart.tsx",
        "sourceSha256": "f66e7e045e525addd4909b51f5f757f198ed8081f3f61970775fb3ce0bc922f1",
        "sourceLineCount": 170,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "camera-orbit",
    "researchImplementationId": "new-core-lab:v1:camera-orbit",
    "sourceGroupId": "new:camera-orbit",
    "label": "空间环绕镜头",
    "batch": "CAMERA_BOUNDARY_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "FOCAL_POINT",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content",
        "focusX",
        "focusY"
      ],
      "optionalProps": [
        "depth",
        "intensity",
        "pitchDegrees",
        "reducedMotion",
        "yawDegrees"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "保留完整场景并以轻微透视终态指示焦点。"
    },
    "mechanismSummary": "围绕明确焦点执行受控 2.5D 轨道位移，不改变场景事实或人物身份。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/camera-boundary-cores.tsx",
      "exportName": "CameraOrbitCore",
      "fileSha256": "6c79a5525f7ec53dd57fa5d6629c3f3c8057c38a9a28c0004d29a4282308719b"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-demoanimations-demozoomfocus-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/DemoAnimations/DemoZoomFocus.tsx",
        "sourceSha256": "7d5af5c2fa57728af82326af484fe3de179f89284095f2bccc00e45478a524bc",
        "sourceLineCount": 180,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-effectanimations-effectdepthoffield-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/EffectAnimations/EffectDepthOfField.tsx",
        "sourceSha256": "dd54fbf73749ef6c64efa52fa36cb7adbd93db194107a657be6a452db1ff08f2",
        "sourceLineCount": 135,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "shotcraft:steep-tilt-glide:steep-tilt-glide",
        "sourcePath": "src/vendor/upstream/shotcraft/demos/camera/steep-tilt-glide/SteepTiltGlide.tsx",
        "sourceSha256": "a926d3c608c6e522e50d64019f396bf1aa8942c7f80726cf2a2aa34a3943d388",
        "sourceLineCount": 324,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "camera-shake",
    "researchImplementationId": "new-core-lab:v1:camera-shake",
    "sourceGroupId": "new:camera-shake",
    "label": "受控镜头震动",
    "batch": "CAMERA_BOUNDARY_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "amplitude",
        "decay",
        "frequency",
        "intensity",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "完整保留场景，不做位移或旋转。"
    },
    "mechanismSummary": "用有限、可衰减的帧函数产生强调性震动，禁止无期限随机抖动。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/camera-boundary-cores.tsx",
      "exportName": "CameraShakeCore",
      "fileSha256": "6c79a5525f7ec53dd57fa5d6629c3f3c8057c38a9a28c0004d29a4282308719b"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:rve-templates-camera-shake-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/camera-shake.tsx",
        "sourceSha256": "f37485422ca6a244d2d7e9eba1305eb547b581fc29bfce9eee0cec00c91752b1",
        "sourceLineCount": 83,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "cross-dissolve",
    "researchImplementationId": "new-core-lab:v1:cross-dissolve",
    "sourceGroupId": "new:cross-dissolve",
    "label": "交叉溶解",
    "batch": "CAMERA_BOUNDARY_CORE",
    "target": "TRANSITION_BOUNDARY",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "BOUNDARY_FROM_SCENE",
      "BOUNDARY_TO_SCENE"
    ],
    "requiredEvidence": [
      "BOUNDARY_PAIR"
    ],
    "inputContract": {
      "requiredProps": [
        "fromScene",
        "toScene"
      ],
      "optionalProps": [
        "intensity",
        "reducedMotion",
        "startFrame",
        "throughBlack",
        "transitionFrames"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 2,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "在边界中点执行直接切换。"
    },
    "mechanismSummary": "只在两个已确认场景之间执行透明度交接，可选短暂经过黑场。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/camera-boundary-cores.tsx",
      "exportName": "CrossDissolveCore",
      "fileSha256": "6c79a5525f7ec53dd57fa5d6629c3f3c8057c38a9a28c0004d29a4282308719b"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:playground-src-compositions-transitions-dissolve-jsx",
        "sourcePath": "src/vendor/upstream/playground/src/compositions/Transitions/Dissolve.tsx",
        "sourceSha256": "39999e7c162b63230d974a9c920b078b3886e1ae3aaf2715c2163aa650b84cf1",
        "sourceLineCount": 137,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:rve-templates-cross-dissolve-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/cross-dissolve.tsx",
        "sourceSha256": "331358ed83f54d16468a72c5b2891b877193558cff4583356c14c0159e06176f",
        "sourceLineCount": 107,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:rve-templates-fade-through-black-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/fade-through-black.tsx",
        "sourceSha256": "bae5adff148cc0d58292d298904bd5f73aa16bb929b22130a2a30a865b8948c4",
        "sourceLineCount": 137,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "liquid-transition",
    "researchImplementationId": "new-core-lab:v1:liquid-transition",
    "sourceGroupId": "new:liquid-transition",
    "label": "液态遮罩转场",
    "batch": "CAMERA_BOUNDARY_CORE",
    "target": "TRANSITION_BOUNDARY",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "BOUNDARY_FROM_SCENE",
      "BOUNDARY_TO_SCENE",
      "FOCAL_POINT"
    ],
    "requiredEvidence": [
      "BOUNDARY_PAIR"
    ],
    "inputContract": {
      "requiredProps": [
        "fromScene",
        "toScene"
      ],
      "optionalProps": [
        "accentColor",
        "intensity",
        "originX",
        "originY",
        "reducedMotion",
        "startFrame",
        "transitionFrames"
      ],
      "capacity": {
        "minimumItems": 2,
        "maximumItems": 2,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "在边界中点使用无形变的直接切换。"
    },
    "mechanismSummary": "以可控液态轮廓作为两个场景之间的遮罩边界，不冒充持续背景。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/camera-boundary-cores.tsx",
      "exportName": "LiquidTransitionCore",
      "fileSha256": "6c79a5525f7ec53dd57fa5d6629c3f3c8057c38a9a28c0004d29a4282308719b"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-transitionanimations-transitionliquidmorph-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/TransitionAnimations/TransitionLiquidMorph.tsx",
        "sourceSha256": "1fbdf3ce8916d4052644bf20d98e3f2db64230a8ce08654dc228eec4703821c9",
        "sourceLineCount": 121,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "channel-distortion",
    "researchImplementationId": "new-core-lab:v1:channel-distortion",
    "sourceGroupId": "new:channel-distortion",
    "label": "色彩通道失真",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "channelOffset",
        "intensity",
        "reducedMotion",
        "scanlineStrength"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示无通道位移的原始场景。"
    },
    "mechanismSummary": "用有限 RGB 通道偏移和扫描撕裂强调场景，不持续破坏文字、人脸或证据。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "ChannelDistortionCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:rve-templates-logo-glitch-reveal-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/logo-glitch-reveal.tsx",
        "sourceSha256": "56d3fcdd0846fe689d706bb04a9c19f44b566fff377298dfeb5c4e184a912041",
        "sourceLineCount": 209,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-effectanimations-effectchromaticaberration-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/EffectAnimations/EffectChromaticAberration.tsx",
        "sourceSha256": "2af2c139b1e467f96ff2e70b2c7832dafecea37c31f917671c9acf10c50d9ee2",
        "sourceLineCount": 109,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-effectanimations-effectvhs-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/EffectAnimations/EffectVHS.tsx",
        "sourceSha256": "d16d8776132e172a473ac26288204b2321478b0786738d5697abd33ff27320db",
        "sourceLineCount": 139,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-logoanimations-logoglitch-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LogoAnimations/LogoGlitch.tsx",
        "sourceSha256": "2d9a1141829c391f7e0601791a536dfb5278cdf6d0c58a6c938d6158e20d80ea",
        "sourceLineCount": 99,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "kaleidoscope-symmetry",
    "researchImplementationId": "new-core-lab:v1:kaleidoscope-symmetry",
    "sourceGroupId": "new:kaleidoscope-symmetry",
    "label": "万花筒对称",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "FOCAL_POINT",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "intensity",
        "reducedMotion",
        "rotationDegrees",
        "segments"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示稳定的低分区对称构图。"
    },
    "mechanismSummary": "围绕明确中心复制镜像切片，限制分区数量和旋转速度。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "KaleidoscopeSymmetryCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-effectanimations-effectkaleidoscope-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/EffectAnimations/EffectKaleidoscope.tsx",
        "sourceSha256": "2e39a3f50aac2b26f04e09b6b3813df0eba01c427bc0916c21f2869da70def04",
        "sourceLineCount": 116,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "light-overlay",
    "researchImplementationId": "new-core-lab:v1:light-overlay",
    "sourceGroupId": "new:light-overlay",
    "label": "光晕与漏光叠层",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "COLOR_THEME",
      "FOCAL_POINT",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "hue",
        "intensity",
        "originX",
        "originY",
        "preset",
        "reducedMotion"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "保留低强度、固定位置的光晕。"
    },
    "mechanismSummary": "以受控混合叠层提供 glow 或 light-leak preset，并保护关键内容区域。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "LightOverlayCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-effectanimations-effectglow-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/EffectAnimations/EffectGlow.tsx",
        "sourceSha256": "82ec09b262d0faf9cbe9b93a7da94f5fc8894c280e610d98d43fec9a4c8ff03a",
        "sourceLineCount": 99,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-effectanimations-effectlightleak-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/EffectAnimations/EffectLightLeak.tsx",
        "sourceSha256": "68e94c9220aa97ba1d45ca938dc359eee798338cd6330b05ba3cc9d678ea3381",
        "sourceLineCount": 101,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "liquid-blob",
    "researchImplementationId": "new-core-lab:v1:liquid-blob",
    "sourceGroupId": "new:liquid-blob",
    "label": "液态团块形变",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "COLOR_THEME",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "intensity",
        "morphAmount",
        "primaryColor",
        "reducedMotion",
        "secondaryColor"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示稳定圆角团块及完整内容。"
    },
    "mechanismSummary": "在一个可控团块轮廓内承载场景内容或色彩，不推断新的信息对象。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "LiquidBlobCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidblob-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidBlob.tsx",
        "sourceSha256": "54ccdacb8a3ba37d62bfd801a74213300c6ca478529cd31df3534182c8bcc00e",
        "sourceLineCount": 149,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidmorphblob-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidMorphBlob.tsx",
        "sourceSha256": "824ed47f0fa669892f31ed2ba354b05cdaf4af2a92dde995ea8af55050617b54",
        "sourceLineCount": 174,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "liquid-flow",
    "researchImplementationId": "new-core-lab:v1:liquid-flow",
    "sourceGroupId": "new:liquid-flow",
    "label": "液体流动",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "COLOR_THEME",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "flowDirection",
        "intensity",
        "preset",
        "primaryColor",
        "reducedMotion",
        "secondaryColor"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示代表性流体终态，不继续流动。"
    },
    "mechanismSummary": "以连续流场式 SVG 表面呈现 wave/oil/drip preset，所有路径由帧确定。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "LiquidFlowCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidfluidwave-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidFluidWave.tsx",
        "sourceSha256": "4a99d2660921f2b2b7671c84e2455bf4e0baf35fa7a503f7d3f99b8b940a79c2",
        "sourceLineCount": 162,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidoilspill-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidOilSpill.tsx",
        "sourceSha256": "b0c9ebec04e7c2eb906a038398c47cb15e480005a1162d1041a7b91299b816fe",
        "sourceLineCount": 168,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidpaintdrip-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidPaintDrip.tsx",
        "sourceSha256": "364ac507ab39aee68b348094085751453c92cedba312ea8c9943b5959388402d",
        "sourceLineCount": 187,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "liquid-ink",
    "researchImplementationId": "new-core-lab:v1:liquid-ink",
    "sourceGroupId": "new:liquid-ink",
    "label": "墨迹扩散与飞溅",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "COLOR_THEME",
      "FOCAL_POINT",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "inkColor",
        "intensity",
        "originX",
        "originY",
        "reducedMotion",
        "splatterCount"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示完整但静止的墨迹构图。"
    },
    "mechanismSummary": "通过确定性墨迹轮廓和飞溅点扩散场景遮罩，限制数量与覆盖范围。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "LiquidInkCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidcalligraphyink-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidCalligraphyInk.tsx",
        "sourceSha256": "b20c41406ff3a5c85aba70b2a2ef4c749342df28d413648c1438cccdba04edef",
        "sourceLineCount": 182,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidinksplash-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidInkSplash.tsx",
        "sourceSha256": "2b063a4ef575582d07e8bc22d675f4e64b398c90f1e0961b2e62566cf9a8b495",
        "sourceLineCount": 111,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidsplatter-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidSplatter.tsx",
        "sourceSha256": "c30b62f4a560a87871afa2a2a99f52544927e58db322c3c6b71859353ec6f6e4",
        "sourceLineCount": 195,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "liquid-ripple",
    "researchImplementationId": "new-core-lab:v1:liquid-ripple",
    "sourceGroupId": "new:liquid-ripple",
    "label": "水滴扩散涟漪",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "COLOR_THEME",
      "FOCAL_POINT",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content",
        "originX",
        "originY"
      ],
      "optionalProps": [
        "amplitude",
        "color",
        "intensity",
        "reducedMotion",
        "ringCount"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示低强度固定波纹或完全移除。"
    },
    "mechanismSummary": "从场景内明确水面焦点扩散多圈衰减涟漪，不复用点击语义。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "LiquidRippleCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidwaterdrop-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidWaterDrop.tsx",
        "sourceSha256": "1dfff3f2d48c4ca2946717644b9f36078b2769c75e6570cd3c52b17ad28b2ef7",
        "sourceLineCount": 200,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "liquid-surface",
    "researchImplementationId": "new-core-lab:v1:liquid-surface",
    "sourceGroupId": "new:liquid-surface",
    "label": "连续液体波面",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "COLOR_THEME",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content"
      ],
      "optionalProps": [
        "amplitude",
        "frequency",
        "intensity",
        "layers",
        "primaryColor",
        "reducedMotion",
        "secondaryColor"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "固定相位显示完整波面。"
    },
    "mechanismSummary": "用显式振幅、频率、相位和层数生成连续 SVG 波面。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "LiquidSurfaceCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:pj-wave",
        "sourcePath": "src/vendor/upstream/playground/src/compositions/WaveAnimations/Wave.tsx",
        "sourceSha256": "db20453571d3abdae0fa08e8a469faaeacb2aa46e551031040fc8f2e9bb7b563",
        "sourceLineCount": 180,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:rve-templates-liquid-wave-tsx",
        "sourcePath": "src/vendor/upstream/rve/templates/liquid-wave.tsx",
        "sourceSha256": "4a3fecd36ac961a33c98cea35f103dbe465aba701751f1cf685dc926eafc0563",
        "sourceLineCount": 50,
        "runtimeStatus": "PASS"
      },
      {
        "effectUnitId": "candidate:scenes-src-scenes-backgroundanimations-backgroundwaves-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/BackgroundAnimations/BackgroundWaves.tsx",
        "sourceSha256": "0fddaa4e57f93eff1f7174341332ae6a2654c2271c2e4e5ca66c659a76ef8c53",
        "sourceLineCount": 75,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  },
  {
    "coreId": "liquid-swirl",
    "researchImplementationId": "new-core-lab:v1:liquid-swirl",
    "sourceGroupId": "new:liquid-swirl",
    "label": "液体旋涡",
    "batch": "SCENE_SURFACE_CORE",
    "target": "SCENE_SURFACE",
    "roleConstraint": "NOT_VISUAL_ROLE",
    "semanticSlots": [
      "COLOR_THEME",
      "FOCAL_POINT",
      "SCENE_NODE"
    ],
    "requiredEvidence": [
      "SCENE_CONTENT"
    ],
    "inputContract": {
      "requiredProps": [
        "content",
        "originX",
        "originY"
      ],
      "optionalProps": [
        "intensity",
        "primaryColor",
        "reducedMotion",
        "secondaryColor",
        "turns"
      ],
      "capacity": {
        "minimumItems": 1,
        "maximumItems": 1,
        "maximumTextCharacters": null
      }
    },
    "controls": {
      "intensity": {
        "minimum": 0,
        "maximum": 1,
        "defaultValue": 0.65
      },
      "durationFrames": {
        "minimum": 30,
        "maximum": 360,
        "defaultValue": 180
      }
    },
    "motionContract": {
      "frameDriven": true,
      "deterministic": true,
      "noCssAnimation": true,
      "noUnseededRandom": true,
      "motionReasonRequired": true,
      "reducedMotionSupported": true,
      "staticFallback": "显示稳定旋涡构图，不继续旋转。"
    },
    "mechanismSummary": "围绕显式焦点产生有限角向位移与旋转色场。",
    "implementation": {
      "path": "desktop/component-lab/new-cores/surface-cores.tsx",
      "exportName": "LiquidSwirlCore",
      "fileSha256": "9627a81519e05855f27f763cc9e3de62d2ad27ecfb0e896b0c8894b6877ecc45"
    },
    "sourceEvidence": [
      {
        "effectUnitId": "candidate:scenes-src-scenes-liquidanimations-liquidswirl-tsx",
        "sourcePath": "src/vendor/upstream/scenes/src/scenes/LiquidAnimations/LiquidSwirl.tsx",
        "sourceSha256": "fdee866c88a2b8e6a7d2cf40036327418b1a4aeb623124fbb0cfa054dd3287b0",
        "sourceLineCount": 170,
        "runtimeStatus": "PASS"
      }
    ],
    "lifecycle": "LAB_VERIFIED",
    "visibility": "LAB_ONLY",
    "labVerificationId": "verification:smart-packaging-new-core-lab-v1:all-21:2026-08-31",
    "agentVisible": false,
    "productionReady": false,
    "visualReviewPassed": true,
    "labReviewAccepted": true,
    "projectAuditionPassed": false,
    "productUserAccepted": false
  }
] as const;

export const SMART_PACKAGING_NEW_CORE_LAB_SUMMARY_V1 = {
  "records": 21,
  "sourceRecords": 40,
  "byBatch": {
    "CAMERA_BOUNDARY_CORE": 4,
    "OBJECT_CORE": 8,
    "SCENE_SURFACE_CORE": 9
  },
  "byTarget": {
    "MEDIA_EVIDENCE": 3,
    "QUANT_DATA": 3,
    "SCENE_SURFACE": 11,
    "SCREEN_UI": 1,
    "TEXT_INFO": 1,
    "TRANSITION_BOUNDARY": 2
  },
  "deterministicFrameDriven": 21,
  "reducedMotionSupported": 21,
  "lifecycleDraft": 0,
  "lifecycleLabVerified": 21,
  "labOnly": 21,
  "visualReviewPassed": 21,
  "labReviewAccepted": 21,
  "projectAuditionPassed": 0,
  "productUserAccepted": 0,
  "productionReady": 0,
  "agentVisible": 0
} as const;

export type SmartPackagingNewCoreLabRecordV1 = (typeof SMART_PACKAGING_NEW_CORE_LAB_RECORDS_V1)[number];
