import React from 'react';
import {AbsoluteFill, OffthreadVideo, staticFile, useCurrentFrame, interpolate, Easing} from 'remotion';
import type {SceneModuleInput} from '../SceneModuleSurface';
const ease=Easing.bezier(.22,1,.36,1);
const box=(left:number,top:number,width?:number,height?:number):React.CSSProperties=>({position:'absolute',left,top,width,height});
export function TalkingHeadStory({id,title,parameters:v,beats,mediaSrc,from}:SceneModuleInput){
 const f=useCurrentFrame(),accent=String(v.accent),paper=String(v.textColor),muted='#929b9f';
 const cue=(label:string)=>beats.find(b=>b.label===label)?.frame??0;
 const progress=(label:string,span=16)=>interpolate(f,[cue(label),cue(label)+span],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease});
 const appear=(label:string):React.CSSProperties=>({opacity:progress(label),transform:`translateY(${(1-progress(label))*18}px)`});
 const video=(x:number,y:number,w:number)=> <div data-editable-object="person" style={{...box(x+Number(v.personX),y+Number(v.personY),w*Number(v.personScale),w*Number(v.personScale)*9/16),borderRadius:14,overflow:'hidden'}}><OffthreadVideo src={mediaSrc.startsWith('/')?mediaSrc:staticFile(mediaSrc)} trimBefore={from} muted style={{width:'100%',height:'100%',objectFit:'contain'}}/></div>;
 const headline=(text:string,sub?:string)=><div data-editable-object="headline" style={box(112,162,1696)}><div style={{fontSize:Number(v.titleSize),fontWeight:550,letterSpacing:-2}}>{text}</div>{sub&&<div style={{fontSize:26,color:muted,marginTop:22}}>{sub}</div>}</div>;
 const phrase=String(v.headline),labels=String(v.labels).split('|');
 const kind=id.replace('dji-','');
 let body:React.ReactNode;
 if(kind==='pain'){
  body=<>{headline(phrase,'拍摄之后，还有这些重复工作。')}{video(112,352,800)}<div data-editable-object="graphics" style={box(1056,348,740)}><div style={{...box(0,54),opacity:1-progress('听素材'),fontSize:52,lineHeight:1.6}}>拍摄之后，<br/><span style={{color:accent}}>工作才刚开始。</span></div>{labels.map((label,i)=><div key={label} style={{...appear(['听素材','删废话','对字幕','加画面'][i]),height:118,display:'flex',alignItems:'baseline',gap:26,color:i===Math.min(3,beats.filter(b=>f>=b.frame&&['听素材','删废话','对字幕','加画面'].includes(b.label)).length-1)?accent:paper}}><span style={{fontSize:18,color:muted,fontFamily:'Menlo'}}>{String(i+1).padStart(2,'0')}</span><span style={{fontSize:48,fontWeight:500}}>{label}</span></div>)}</div></>;
 }else if(kind==='introduce'){
  body=<>{video(112,320,760)}<div data-editable-object="headline" style={{...box(1008,316,800),...appear('产品名称')}}><div style={{fontSize:22,color:accent,letterSpacing:4}}>把重复工作交给工具</div><div style={{fontSize:100,fontWeight:550,letterSpacing:-5,marginTop:34}}>Codex Cut</div><div style={{fontSize:42,marginTop:16}}>{phrase}</div><div style={{fontSize:25,color:muted,marginTop:45}}>口播素材　→　剪辑　→　包装</div></div></>;
 }else if(kind==='smart'){
  const cues=['保留人物','强调一句话','大数字','图片','录屏','AI对话'];let mode=-1;cues.forEach((k,i)=>{if(f>=cue(k))mode=i;});const label=mode<0?'分析内容':cues[mode];
  body=<>{headline(phrase)}{video(112,398,640)}<div data-editable-object="graphics" style={box(864,354,944,520)}><div style={{fontSize:21,color:accent,marginBottom:30}}>{mode<0?'先理解这一段说了什么':labels[mode]}</div><div key={label} style={appear(label)}>
  {mode<0?<><div style={{fontSize:52,lineHeight:1.6}}>每段内容，<br/>找到合适的表达。</div><div style={{fontSize:24,color:muted,marginTop:26}}>人物 · 重点 · 信息关系</div></>:mode===0?<><div style={{fontSize:62,lineHeight:1.5}}>让讲述者<br/><span style={{color:accent}}>成为主角。</span></div><div style={{fontSize:24,color:muted,marginTop:30}}>有些时候，不需要额外画面。</div></>:mode===1?<div style={{fontSize:70,lineHeight:1.5,paddingTop:20}}>把时间留给<br/><span style={{color:accent}}>内容与创意。</span></div>:mode===2?<><div style={{fontSize:164,color:accent,fontWeight:600,lineHeight:1.2}}>3,600</div><div style={{fontSize:30,marginTop:16}}>张画面 / 分钟</div><div style={{fontSize:19,color:muted,marginTop:24}}>数字表达示意 · 60fps</div></>:mode===3?<><svg width="660" height="320" viewBox="0 0 660 320" style={{borderRadius:14}}><rect width="660" height="320" fill="#28363c"/><circle cx="495" cy="80" r="32" fill={accent}/><path d="M0 320L180 80 390 320M190 320L440 130 660 320" fill="#849b83"/></svg><div style={{fontSize:22,color:muted,marginTop:22}}>图片表达示意</div></>:mode===4?<><div style={{background:'#222b2e',padding:28,borderRadius:14,width:770}}><div style={{fontSize:19,color:muted}}>操作录屏 · 示意</div><div style={{height:136,marginTop:24,background:'#303c3d',display:'flex',alignItems:'center',justifyContent:'center',fontSize:32}}>文字对应画面</div><div style={{display:'flex',gap:7,marginTop:20}}>{['选中','调整','完成'].map((t,i)=><div key={t} style={{flex:1,padding:18,background:i===1?'#596646':'#344137',color:i===1?accent:paper,fontSize:22}}>{t}</div>)}</div></div></>:<><div style={{fontSize:19,color:muted,marginBottom:22}}>AI 对话 · 示意</div><div style={{padding:'22px 28px',background:'#303a30',borderRadius:14,fontSize:29,marginLeft:150}}>这里应该强调什么？</div><div style={{...appear('AI对话'),padding:'24px 28px',fontSize:35,lineHeight:1.6,marginTop:20}}>先找到重点，<br/><span style={{color:accent}}>再决定怎样呈现。</span></div></>}
  </div></div></>;
 }else if(kind==='compatibility'){
  const content=progress('内容'),position=progress('人物位置'),fit=progress('画幅'),replace=progress('更换'),adjust=progress('调整'),remove=progress('删除');
  body=<>{headline(phrase)}{video(112,366,920)}<div data-editable-object="graphics"><div style={{...box(180+position*70,422+position*350,620),opacity:(1-remove)*.95,transform:`scale(${1-adjust*.12})`,transformOrigin:'left center'}}><div style={{fontSize:42,padding:'16px 24px',borderRadius:10,background:replace>.5?'#dff4a3':'#f2f0e9',color:'#202824'}}>{replace>.5?'把重点讲清楚':'让效果服务内容'}</div><div style={{fontSize:18,color:position>.9?accent:'#f3a99d',marginTop:14}}>{position>.9?'✓ 避让人物':'× 遮挡人物 · 调整前示意'}</div></div><div style={box(1150,382,650)}>{labels.slice(0,3).map((t,i)=><div key={t} style={{...appear(['内容','人物位置','画幅'][i]),marginBottom:45,fontSize:42}}><span style={{color:accent,marginRight:20}}>✓</span>{t}</div>)}<div style={{...appear('更换'),fontSize:24,marginTop:62,display:'flex',gap:28}}>{['更换','调整','删除'].map((t,i)=><span key={t} style={{color:i===(remove>.1?2:adjust>.1?1:0)?accent:muted}}>{t}</span>)}</div></div><div style={{...box(112,920),fontSize:20,color:muted,opacity:content}}>位置与样式调整示意</div><div style={{...box(112,366,920,517.5),boxSizing:'border-box',border:`2px solid ${accent}`,borderRadius:14,opacity:fit*(1-progress('更换'))}}/></div></>;
 }else if(kind==='library'){
  const stages=['运行','分类','适配','人工评审'];
  body=<>{headline(phrase,'先验证，再进入生产。')}{video(112,348,640)}<div data-editable-object="graphics" style={box(864,344,944)}><div style={{fontSize:20,color:muted}}>组件筛选流程示意</div><div style={{...box(0,65),opacity:1-progress('实验室')}}><div style={{fontSize:48}}>收集的组件</div><div style={{display:'flex',gap:34,marginTop:42}}>{['文字','信息','对比'].map(t=><span key={t} style={{fontSize:30,color:accent,padding:'20px 26px',background:'#28322e',borderRadius:10}}>{t}</span>)}</div><div style={{fontSize:24,color:muted,marginTop:32}}>进入实验室，逐项验证。</div></div><div style={{fontSize:48,marginTop:25,...appear('实验室')}}>视觉实验室</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'36px 48px',marginTop:42}}>{stages.map((s,i)=><div key={s} style={{...appear(s),height:118}}><div style={{fontSize:18,color:muted,fontFamily:'Menlo',marginBottom:16}}>0{i+1}</div><div style={{fontSize:38,color:progress(s)>.9?accent:paper}}>{labels[i]}</div></div>)}</div><div style={{...appear('生产库'),marginTop:34,fontSize:46,color:accent}}>通过评审 → 生产库</div></div></>;
 }else{
  const focus=progress('内容'),creative=progress('创意');
  body=<>{video(112,292,920)}<div data-editable-object="headline" style={box(1136,298,680)}><div style={{fontSize:24,color:muted}}>我们的目标很简单</div><div style={{...appear('减少重复'),fontSize:38,lineHeight:1.6,marginTop:28,opacity:progress('减少重复')*(1-focus*.65)}}>少一些<br/>重复的体力劳动。</div><div style={{...appear('留给'),fontSize:28,color:muted,marginTop:38}}>把更多时间留给</div><div style={{...appear('内容'),fontSize:100,color:accent,letterSpacing:-4,marginTop:16}}>{labels[0]}<span style={{fontSize:38,color:paper,opacity:creative,margin:'0 22px'}}>与</span><span style={{opacity:creative}}>{labels[1]}</span></div></div><div data-editable-object="graphics" style={{...box(112,902),...appear('创意'),fontSize:25,color:muted}}>{phrase}</div></>;
 }
 return <AbsoluteFill style={{background:String(v.background),color:paper,fontFamily:'PingFang SC, sans-serif'}}><div style={{...box(112,72),fontSize:18,color:muted,letterSpacing:2}}>CODEX CUT <span style={{margin:'0 20px',color:'#374044'}}>/</span>{title}</div>{body}</AbsoluteFill>;
}
