/** Capability aliases only. No reference implementation or recipe text is imported. */
export const REFERENCE_CORE_ALIASES:Readonly<Record<string,string>>={
 'bar-chart-growth':'bar-chart',
 'chart-grow':'bar-chart',
 'chat-gpt':'chat-thread',
 'chat-message-flow':'chat-thread',
 'claude-code':'code-diff',
 'douyin-follow-card':'social-follow-card',
 'focus-dim-spotlight':'spotlight-scan',
 'line-chart-story-draw':'line-chart',
 'logo-enter':'brand-lockup',
 'motion-blur-slam-in':'smear-trail',
 'number-counter':'numeric-counter',
 'numbered-step-stack':'list-sequence',
 'shape-wipe-transition':'geometric-wipe',
 'split-compare-slider':'before-after',
 'stack-fan-out':'card-deck',
 'stage-keyframe-tour':'media-tour',
 'step-timeline-vertical':'step-progress',
 'subscribe-cta':'social-follow-card',
 'terminal-typing-log':'terminal-type',
 'timeline-photo-strip':'media-carousel',
 'typewriter-reveal':'typewriter',
 'unit-grid-proportion':'unit-chart',
 'x-follow-card':'social-follow-card',
};
